default_job = "clippy"

[jobs.clippy]
command = ["cargo", "clippy", "--target-dir", "target/bacon", "--color", "always", "--all-targets", "--", "-W", "clippy::pedantic"]
need_stdout = false

[exports.locations]
auto = true
path = ".bacon-locations"


[jobs.fmt]
command = ["cargo", "+nightly", "fmt"]
need_stdout = false
