[workspace]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
members = [
  "apps/asset_store",
  "apps/link-cli",
  "apps/link-ui/src-tauri",
  "apps/linkd",
  "apps/myko/backplane",
  "libs/myko/rs",
  "libs/link/core",
  "libs/link/rpc/rs",
  "libs/myko/macros",
  "libs/entities/rs",
  "libs/sdk/rs",
  "libs/sync/core",
  "libs/sync/ffi",
  "apps/sync_server",
  "libs/rs-macros",
  "libs/opencv",
  "libs/asset-store/core", "apps/server_rs", "libs/autosocket",
]
