[package]
name = "myko-macros"
version = "4.3.0-canary.2"
edition = "2024"
description = "myko macros"
license = "AGPL-3.0-or-later"
documentation = "https://docs.rs/myko-macros"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.flux]
tasks = ["check", "build", "test", "lint", "publish"]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
syn.workspace = true
quote.workspace = true
