[package]
name = "myko-server"
version = "4.0.0-canary.20"
edition = "2024"
description = "Myko server runtime — WebSocket, Kafka, peer federation"
license = "AGPL-3.0-or-later"

[dependencies]
# Internal
myko-rs.workspace = true

# Async runtime
tokio.workspace = true
tokio-tungstenite.workspace = true
tungstenite.workspace = true
tokio-util.workspace = true

# Kafka
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
openssl = { version = "0.10.35", features = ["vendored"] }
postgres = "0.19.9"

# Async utilities
futures-util.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true

# Misc
uuid.workspace = true
chrono.workspace = true
log.workspace = true
hyphae.workspace = true
inventory = "0.3.21"
dashmap.workspace = true
flume.workspace = true

[features]
default = []
inspector = ["hyphae/inspector"]
trace = ['hyphae/trace']