[package]
name = "myko-rs"
version = "3.0.0-canary.809"
edition = "2024"
description = "myko in rust"
license = "AGPL-3.0-or-later"
documentation = "https://docs.rs/myko-rs"
homepage = "https://docs.rs/myko-rs"
repository = "https://github.com/ignition-is-go/rship"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["js"] }
partially.workspace = true
futures.workspace = true
futures-util.workspace = true
async-stream.workspace = true
tokio.workspace = true
tungstenite.workspace = true
tokio-tungstenite.workspace = true
async-trait.workspace = true
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
myko-macros.workspace = true
openssl = { version = "0.10.35", features = ["vendored"] }
rmp.workspace = true
rmp-serde.workspace = true
md5 = "0.7.0"
tokio-util.workspace = true
tokio-stream.workspace = true
pin-project-lite.workspace = true
url.workspace = true
chrono.workspace = true
log.workspace = true
ractor.workspace = true
anyhow.workspace = true
autosocket.workspace = true
ts-rs = { workspace = true, features = ["serde-json-impl"] }
inventory = "0.3.21"
dprint-plugin-typescript = "0.95.12"
tantivy = "0.22"
crossbeam.workspace = true
flume.workspace = true
hypha.workspace = true
dashmap.workspace = true

[features]
default = []
bench = []

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
num_cpus = "1.16"

[[bench]]
name = "gateway"
harness = false
required-features = ["bench"]
