
[tasks.gen]
command = "cargo"
args = ["run", "--bin", "typegen", "--target-dir", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/typegen"]

[tasks.gen-watch]
command = "cargo"
args = ["watch", "-i", "bindings/", "-x", "run --bin typegen --target-dir ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/typegen"]
