[package]
name = "myko-leptos"
version = "4.2.0-canary.1"
description = "Myko client for leptos"
license = "AGPL-3.0-or-later"
edition.workspace = true
authors.workspace = true

[package.metadata.flux]
tasks = ["check", "build", "test", "lint", "publish"]

[dependencies]
leptos = { version = "0.8" }
serde = { workspace = true }
myko = { workspace = true }

[lints]
workspace = true
