[package]
name = "myko-leptos"
version = "4.0.0-canary.16"
description = "Myko client for leptos"
license = "AGPL-3.0-or-later"
edition.workspace = true
authors.workspace = true

[dependencies]
leptos = { version = "0.8" }
serde = { workspace = true }
myko-rs = { workspace = true }

[lints]
workspace = true