export const MYKO_ITEM_TYPE = '__MYKO_ITEM_TYPE__'

export const MYKO_ITEM_BELONGS_TO_KEY = '__MYKO_ITEM_BELONGS_TO_KEY__'
export const MYKO_ITEM_OWNS_MANY_KEY = '__MYKO_ITEM_OWNS_MANY_KEY__'

export const MYKO_EVENT_HANDLER = '__MYKO_EVENT_HANDLER__'
export const MYKO_EVENT = '__MYKO_EVENT__'

export const MYKO_HANDLER_QUERY_ID_KEY = '__MYKI_HANDLER_QUERY_ID_KEY__'
export const MYKO_QUERY_ID_KEY = '__MYKO_QUERY_ID_KEY__'
export const MYKO_QUERY_ITEM_TYPE_KEY = '__MYKO_QUERY_ITEM_TYPE_KEY__'

export const MYKO_HANDLER_COMMAND_ID_KEY = '__MYKO_HANDLER_COMMAND_KEY__'
export const MYKO_COMMAND_ID_KEY = '__MYKO_COMMAND_ID_KEY__'

export const MYKO_SAGA_METADATA = '__MYKO_SAGA__'
