// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SocketConnectionStatus = { "type": "idle" } | { "type": "disconnected" } | { "type": "connecting", "data": string } | { "type": "reconnecting", "data": string } | { "type": "connected", "data": string };
