$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  language: 'rust'
  layer: 'application'

tasks:
  build:
    options:
      cache: false
    command: 'cargo'
    args:
      - 'build'
      - '--release'
      - '--target-dir'
      - 'target'
