name: Release

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main, dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
          fetch-tags: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: oven-sh/setup-bun@v2
      - uses: Swatinem/rust-cache@v2

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: bun install
      - run: cargo install cargo-flux
      - run: cargo flux run release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          JSR_TOKEN: ${{ secrets.JSR_TOKEN }}
